app: meet
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.

service: auth-server

provider:
  name: aws
  runtime: nodejs18.x
  region: us-west-1
  timeout: 30 # optional, in seconds, default is 6
  environment:
    CLIENT_ID: ${file(config.json):web.client_id}
    CLIENT_SECRET: ${file(config.json):web.client_secret}
    CALENDAR_ID: ${file(config.json):web.calendar_id}

functions:
  getAuthURL:
    handler: handler.getAuthURL
    events:
      - http:
          path: api/get-auth-url
          method: get
          cors:
            origin: "https://jdeebs.github.io"
            headers:
              - Content-Type
              - Authorization
            allowCredentials: true
  getAccessToken:
    handler: handler.getAccessToken
    events:
      - http:
          path: api/token/{code}
          method: get
          cors:
            origin: "https://jdeebs.github.io"
            headers:
              - Content-Type
              - Authorization
            allowCredentials: true
  getCalendarEvents:
    handler: handler.getCalendarEvents
    events:
      - http:
          path: api/get-events/{access_token}
          method: get
          cors:
            origin: "https://jdeebs.github.io"
            headers:
              - Content-Type
              - Authorization
            allowCredentials: true
