# app and org for use with dashboard.serverless.com
service: auth-server
org: jdeebs
app: meet

# You can pin your service to only deploy with a specific Serverless version
frameworkVersion: "4"

provider:
  name: aws
  runtime: nodejs18.x
  region: us-west-1
  timeout: 30 # optional, in seconds, default is 6
  environment:
    CLIENT_ID: ${file(config.json):client_id}
    CLIENT_SECRET: ${file(config.json):client_secret}
    CALENDAR_ID: ${file(config.json):calendar_id}

functions:
  getAuthURL:
    handler: handler.getAuthURL
    events:
      - http:
          path: get-auth-url
          method: get
          cors:
            origin: "*"
            headers:
              - Content-Type
              - Authorization
            allowCredentials: true
  getAccessToken:
    handler: handler.getAccessToken
    events:
      - http:
          path: token/{code}
          method: get
          cors:
            origin: "*"
            headers:
              - Content-Type
              - Authorization
            allowCredentials: true
  getCalendarEvents:
    handler: handler.getCalendarEvents
    events:
      - http:
          path: get-events/{access_token}
          method: get
          cors:
            origin: "*"
            headers:
              - Content-Type
              - Authorization
            allowCredentials: true
