# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: jdeebs
app: meet
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.

service: auth-server

provider:
  name: aws
  runtime: nodejs18.x
  region: us-west-1
  timeout: 30 # optional, in seconds, default is 6
  environment:
    CLIENT_ID: ${file(config.json):client_id}
    CLIENT_SECRET: ${file(config.json):client_secret}
    CALENDAR_ID: ${file(config.json):calendar_id}

functions:
  getAuthURL:
    handler: handler.getAuthURL
    events:
      - http:
          path: get-auth-url
          method: get
  getAccessToken:
    handler: handler.getAccessToken
    events:
      - http:
          path: token/{code}
          method: get
  getCalendarEvents:
    handler: handler.getCalendarEvents
    events:
      - http:
          path: get-events/{access_token}
          method: get
